default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: walkman
  pool: 5

development:
  <<: *default
  database: Blog_development4

test:
  <<: *default
  database: Blog_test

production:
  <<: *default
  database: Blog_production
  username: Blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
